'use client'

import { useRef } from 'react'
import { Download } from 'lucide-react'
import BunnySVG from './BunnySVG'
import type { Child, ScoreEntry, RewardItem } from '@/lib/types'

interface ExportReportProps {
  child: Child
  entries: ScoreEntry[]
  rewards: RewardItem[]
  month: string // "YYYY-MM"
}

export default function ExportReport({ child, entries, rewards, month }: ExportReportProps) {
  const reportRef = useRef<HTMLDivElement>(null)

  const monthDate = new Date(month + '-01')
  const monthLabel = monthDate.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })
  const totalCarrots = entries.reduce((sum, e) => sum + e.points, 0)
  const earnedRewards = rewards.filter(r => r.carrot_threshold <= totalCarrots)

  const handleExport = async () => {
    if (!reportRef.current) return
    const html2canvas = (await import('html2canvas')).default
    const jsPDF = (await import('jspdf')).default

    const canvas = await html2canvas(reportRef.current, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#FFF9FB'
    })

    const imgData = canvas.toDataURL('image/png')
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
    const pdfWidth = pdf.internal.pageSize.getWidth()
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width

    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight)
    pdf.save(`${child.name}-${month}-report.pdf`)
  }

  return (
    <div>
      <button
        onClick={handleExport}
        className="flex items-center gap-2 bg-accent text-app-text font-bold px-4 py-2 rounded-2xl hover:bg-accent/70 transition shadow"
      >
        <Download size={18} />
        Export PDF
      </button>

      {/* Hidden export template */}
      <div className="fixed -left-[9999px] top-0">
        <div
          ref={reportRef}
          className="w-[595px] p-10 bg-background font-baloo"
          style={{ fontFamily: "'Baloo 2', cursive" }}
        >
          {/* Header */}
          <div className="text-center mb-6">
            <div className="text-4xl mb-2">🐰 Good Kid Score App 🥕</div>
            <h1 className="text-3xl font-bold text-app-text">Monthly Report</h1>
            <p className="text-app-text/60 text-lg">{monthLabel}</p>
          </div>

          {/* Child Info */}
          <div className="flex items-center gap-4 bg-white rounded-3xl p-5 mb-6 border-2 border-primary/30">
            <BunnySVG color={child.bunny_color} size={80} />
            <div>
              <h2 className="text-2xl font-bold text-app-text">{child.name}</h2>
              <div className="flex items-center gap-2 mt-1">
                <span className="text-3xl">🥕</span>
                <span className="text-3xl font-bold text-app-text">{totalCarrots}</span>
                <span className="text-app-text/60">carrots earned</span>
              </div>
            </div>
          </div>

          {/* Entries */}
          <div className="mb-6">
            <h3 className="text-lg font-bold text-app-text mb-3">Score History</h3>
            <div className="space-y-2">
              {entries.sort((a, b) => a.date.localeCompare(b.date)).map(entry => (
                <div key={entry.id} className="flex items-center justify-between bg-white rounded-2xl px-4 py-2 border border-lavender">
                  <div>
                    <span className="font-semibold text-app-text">{new Date(entry.date + 'T00:00:00').toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</span>
                    {entry.note && <span className="text-app-text/60 text-sm ml-2">— {entry.note}</span>}
                  </div>
                  <span className="font-bold text-app-text">🥕 ×{entry.points}</span>
                </div>
              ))}
              {entries.length === 0 && (
                <p className="text-app-text/50 text-center py-4">No entries this month</p>
              )}
            </div>
          </div>

          {/* Rewards Earned */}
          {earnedRewards.length > 0 && (
            <div>
              <h3 className="text-lg font-bold text-app-text mb-3">🎉 Rewards Earned!</h3>
              <div className="space-y-2">
                {earnedRewards.map(reward => (
                  <div key={reward.id} className="flex items-center gap-3 bg-secondary/30 rounded-2xl px-4 py-2">
                    <span>🏆</span>
                    <span className="font-semibold text-app-text">{reward.reward_description}</span>
                    <span className="text-app-text/60 text-sm ml-auto">({reward.carrot_threshold} 🥕)</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Footer */}
          <div className="text-center mt-8 text-app-text/40 text-sm">
            Generated by Good Kid Score App
          </div>
        </div>
      </div>
    </div>
  )
}
