'use client'

import { useRef } from 'react'
import { Download } from 'lucide-react'
import type { RewardItem } from '@/lib/types'

interface ExportRewardsTableProps {
  rewards: RewardItem[]
}

export default function ExportRewardsTable({ rewards }: ExportRewardsTableProps) {
  const reportRef = useRef<HTMLDivElement>(null)

  const sorted = [...rewards].sort((a, b) => a.carrot_threshold - b.carrot_threshold)

  const handleExport = async () => {
    if (!reportRef.current) return
    const html2canvas = (await import('html2canvas')).default
    const jsPDF = (await import('jspdf')).default

    const canvas = await html2canvas(reportRef.current, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#FFF9FB'
    })

    const imgData = canvas.toDataURL('image/png')
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
    const pdfWidth = pdf.internal.pageSize.getWidth()
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width

    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight)
    pdf.save(`rewards-table.pdf`)
  }

  return (
    <div>
      <button
        onClick={handleExport}
        className="flex items-center gap-2 bg-accent text-app-text font-bold px-4 py-2 rounded-2xl hover:bg-accent/70 transition shadow"
      >
        <Download size={18} />
        Export PDF
      </button>

      <div className="fixed -left-[9999px] top-0">
        <div
          ref={reportRef}
          className="w-[500px] p-10 bg-background"
          style={{ fontFamily: "'Microsoft JhengHei', 'Baloo 2', cursive" }}
        >
          <div className="text-center mb-6">
            <div className="text-4xl mb-2">🎁</div>
            <h1 className="text-3xl font-bold text-app-text">Rewards Table</h1>
            <p className="text-app-text/60">Earn carrots 🥕 to unlock these rewards!</p>
          </div>

          <div className="space-y-3">
            {sorted.map((reward, i) => (
              <div key={reward.id} className="flex items-center gap-4 bg-white rounded-2xl px-5 py-3 border-2 border-lavender">
                <span className="text-2xl font-bold text-app-text/30">{i + 1}</span>
                <div className="flex items-center gap-1 bg-lemon rounded-xl px-3 py-1">
                  <span className="text-xl font-bold text-app-text">{reward.carrot_threshold}</span>
                  <span>🥕</span>
                </div>
                <span className="text-app-text/50 font-bold">=</span>
                <span className="flex-1 font-semibold text-app-text">{reward.reward_description}</span>
              </div>
            ))}
            {sorted.length === 0 && (
              <p className="text-center text-app-text/40 py-8">No rewards set yet.</p>
            )}
          </div>

          <div className="text-center mt-8 text-app-text/40 text-sm">
            Generated by Good Kid Score App
          </div>
        </div>
      </div>
    </div>
  )
}
